BASH:
  - "(Bash|bash|BASH)"
JavaScript:
  - "(JavaScript|JAVASCRIPT|Javascript|javascript|JS|js)"
Python:
  - "(Python|PYTHON|python)"
enhancement:
  - "(enhancement)"
Easy:
  - "(Easy|easy)"  
Medium:
  - "(Medium|medium)"
Hard:
  - "(Hard|hard)"
bug:
  - "(bug|Bug|BUG)"  
Up-For-Grab:
  - "(up for grab)"  
Urgent:
  - "(urgent|URGENT|Urgent)"  
documentation:
  - "(documentation)"
No-Code:
  - "(No Code)"  