name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        issue-message: 'Hi thanks for creating your first issue. '
        pr-message: 'Congratulations!! for making your first PR, admin will review it soon and merge finally.'